language: java

os: linux

dist: xenial

install: true

jdk: oraclejdk8

services:
    - xvfb

git:
    depth: false

addons:
    chrome: stable
    firefox: latest

before_script:
    - export DISPLAY=:99.0

jobs:
    include:
        - stage: Maven
          script: mvn verify
        - stage: Gradle
          script: ./gradlew test
